### ISSUE TITLE
Add the label for using multiple servers

### ISSUE THREAD

**Issue by vmotov** [raffis/mongodb-query-exporter#161]
#### Is your feature request related to a problem? Please describe

When I use multiple MongoDB servers, such as test and prod, I can't differentiate them in metrics
Let say, I defined servers below 

```
servers:
- name: test
  uri: 'mongodb://readuser:readpassword@hostname_test:27017'
- name: prod
  uri: 'mongodb://readuser:readpassword@hostname_prod:27017'
```

And next I want to use both servers for one metric 
```
servers: [] #Can also be empty, if empty the metric will be used for every server defined
```
But in the end, on the /metrics page, I see only one metric. 
```
mongodb_query_exporter_query_total{aggregation="aggregation_4",result="SUCCESS",server="prod"} 1
mongodb_query_exporter_query_total{aggregation="aggregation_4",result="SUCCESS",server="test"} 1
sample_metric_name_gauge{mylabel="mylabel"} 1
```

And I would like to see something like this
```
mongodb_query_exporter_query_total{aggregation="aggregation_4",result="SUCCESS",server="prod"} 1
mongodb_query_exporter_query_total{aggregation="aggregation_4",result="SUCCESS",server="test"} 1
sample_metric_name_gauge{server="test", mylabel="mylabel"} 1
sample_metric_name_gauge{server="prod", mylabel="mylabel"} 3
```
#### Describe the solution you'd like
Is it possible to add a label with the name of the server to make difference between them?
Please let me know if such a possibility already exists. I didn't find this in Readme
