### ISSUE TITLE
Different instance like query-exporter

### ISSUE THREAD

**Issue by xuanyuanaosheng** [raffis/mongodb-query-exporter#4]
we want to use this to connect different mongodb instance? could you please give some example?

https://github.com/albertodonato/query-exporter

```
databases:
  db1:
    dsn: sqlite://
    connect-sql:
      - PRAGMA application_id = 123
      - PRAGMA auto_vacuum = 1
    labels:
      region: us1
      app: app1
  db2:
    dsn: sqlite://
    keep-connected: false
    labels:
      region: us2
      app: app1
```
