### ISSUE TITLE
[Question] Is is possible to use a variable database ?

### ISSUE THREAD

**Issue by VannTen** [raffis/mongodb-query-exporter#49]
I'm working on setting up the exporter for our project.

We have autodeployed dev environnements with one database for each environment, is it possible to make the `database` value inside the config depend on a variable environment ?

For example:
```
aggregations:
  - database:  ${DB}
    collection: collection_x
    ...
```
