### ISSUE TITLE
[Question] Metric with some label at value == 0

### ISSUE THREAD

**Issue by VannTen** [raffis/mongodb-query-exporter#52]
I'm not sure I completely understand the usage of labels and constLabels :

I would like to export a metric with a different label value depending on one field in the collection, (with a bounded set of values):
```yaml
      metrics:
      - name: a_metric
        type: gauge
        value: count
        overrideEmpty: true 
        emptyValue: 0       
        labels: [state]
      cache: 0
      mode: pull
      pipeline: |
        [
          {"$group": {
              _id: "$some_state",
              count: {
                $sum:1
              }
            }},
          {"$project": {
              _id: 0,
              state: "$_id",
              count: 1
            }}
        ]
```
Let's say `some_state` can be `A`, `B`, or `C`
If I understand correctly, they would be exported like so : 
```
a_metric{state="A"} x
a_metric{state="B"} y
a_metric{state="C"} z
```
Sometimes there is no document with `some_state==C`
Can I force the exporter to still export `a_metric{state="C"} 0` (value 0) in that case ? (constLabels seems to be related to that, but I'm not quite sure).

Thanks !
