### ISSUE TITLE
panic: Unsupported Config Type ""

### ISSUE THREAD

**Issue by rockonedege** [raffis/mongodb-query-exporter#63]
#### Describe the bug
using docker container ghcr.io/raffis/mongodb-query-exporter:v1.0.0, to try it.  I had 2 problems
- cannot open file  /etc/mongodb-query-exporter/config.yaml, even it's mapped already. I had it worked around by changing it to /tmp
- then I have this mythic error: panic: Unsupported Config Type "" with all v1,v2,v3 config.yml files from folder /example. I actually  modified seom filelds and them restored the original files. all the same error.

below is my docker compose snippet 
```yml
  mongodb_query_exporter:
  # https://github.com/raffis/mongodb-query-exporter
  # docker pull ghcr.io/raffis/mongodb-query-exporter:v1.0.0
    image: ghcr.io/raffis/mongodb-query-exporter:v1.0.0
    container_name: mongodb_query_exporter
    hostname: mongodb_query_exporter
    environment:
      - "MDBEXPORTER_CONFIG=/tmp"
    volumes:
      - ./:/tmp
```
#### Expected behavior
it should run as expected, with out error in parsing config.yml, or if it does, it better tells me where it is(line# , fileds etc.) 

#### Environment
 - mongodb-query-exporter version:  v1.0.0
 - Deployed as: docker
#### Additional context
None
