### ISSUE TITLE
metric setting has no effect

### ISSUE THREAD

**Issue by rockonedege** [raffis/mongodb-query-exporter#79]
I tried to set metrics as `counter` in `config.yml` as follows:
```yml
- database: edge
  collection: barcode_counter_log
  servers: [lgs11l] #Can also be empty, if empty the metric will be used for every server defined
  metrics:
  - name: lgs11l_sw_product_total
    type: counter  #Can also be empty, the default is gauge
    help: 'accumulated parts number'
    value: createTime
    overrideEmpty: true # if an empty result set is returned..
    emptyValue: 0       # create a metric with value 0
    labels: []
    constLabels: []
  mode: pull
  pipeline: |
    [
       {"$count":"createTime"}
    ]
```

however, the query always returns  `gauge`,
```yml
# HELP lgs11l_sw_product_total accumulated parts number
# TYPE lgs11l_sw_product_total gauge
lgs11l_sw_product_total 7
```

Am I doing anything wrong?
