### ISSUE TITLE
mapped folder '/etc/mongodb-query-exporter' worked in v1 but not in v2  

### ISSUE THREAD

**Issue by rockonedege** [raffis/mongodb-query-exporter#89]
#### Describe the bug

It's been working well with the following setting
```yml
  mongodb-query-exporter:
  # https://github.com/raffis/mongodb-query-exporter
  # docker pull ghcr.io/raffis/mongodb-query-exporter:v1.0.0
    image: ghcr.io/raffis/mongodb-query-exporter:v1.0.0
    container_name: mongodb-query-exporter
    hostname: mongodb-query-exporter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./:/etc/mongodb-query-exporter
    restart: always
    ports:
      - 9412:9412
```

I just removed `:v1.0.0`,  and then `docker compose pull` to upgrade to `latest` and `2.0.1`, it could not find the `config.yaml` anymore
It was the same when I added `2.0.1`.

The error was as follows:
```

the following setting that used to work just stopped with 


main.main()

	/home/runner/work/mongodb-query-exporter/mongodb-query-exporter/cmd/root.go:117 +0x25

panic: Config File "config" Not Found in "[/home/nonroot/.mongodb_query_exporter /etc/mongodb_query_exporter]"

```
after quite a few trials, I could get it work with the olc `/tmp` trick
```
  mongodb-query-exporter:
  # https://github.com/raffis/mongodb-query-exporter
  # docker pull ghcr.io/raffis/mongodb-query-exporter:2.0.1
    image: ghcr.io/raffis/mongodb-query-exporter:2.0.1
    container_name: mongodb-query-exporter
    hostname: mongodb-query-exporter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - MDBEXPORTER_CONFIG=/tmp/config.yaml
    volumes:
      - ./:/tmp
    restart: always
    ports:
      - 9412:9412
```

#### To Reproduce
- used the above snippet inside a `docker-compose.yml` file
- run `docker compose up` and check the log for the error message
```
panic: Config File "config" Not Found in "[/home/nonroot/.mongodb_query_exporter /etc/mongodb_query_exporter]"
```
#### Expected behavior
config.yaml being found as documented

#### Environment
 - mongodb-query-exporter [version:v2.0.1]
 - prometheus version: [docker latest]
 - MongoDB version: [v6]
 - Deployed as: [docker]

#### Additional context

In retrospect, I suspect some fundamental user-related access right handling is missing in the code or documentation, which yields mapped file cannot be aceessed by the app inside docker container. And using `/tmp` bypassed it.
